### ISSUE TITLE
Bower resolution failure on master

### ISSUE THREAD

**Issue by owickstrom** [purescript-hyper/purescript-trout-client#9]
It seems after the merge of https://github.com/owickstrom/purescript-trout-client/pull/8 (which passed CI) the `bower install` isn't working on master CI. I've tried to mess around with the versioning constraints, and even remove the use of JQuery in the example application, but I've failed to get it to resolve.

I don't know if Bower is still used much in the PS community, but this situation is quite annoying. Package sets would perhaps be better? I can't really say as I'm too inactive. :/

**Comment by owickstrom** [comment]
@nicholassaunders ideas?

**Comment by nsaunders** [comment]
@owickstrom, see my comment in [purescript-hypertrout#13](https://github.com/owickstrom/purescript-hypertrout/issues/13). I would be inclined to use the same setup here as well.

**Comment by owickstrom** [comment]
Yeah, that would be nice!

**Comment by nsaunders** [comment]
Should be resolved by #14
